name: Release Notes Simple

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Obtener último tag
        id: lasttag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_OUTPUT

      - name: Mostrar commits desde el último tag
        run: |
          echo "Commits desde ${{ steps.lasttag.outputs.tag }} hasta HEAD:"
          git log ${{ steps.lasttag.outputs.tag }}..HEAD --pretty=format:"- %s"
