name: Release Notes Automático

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Obtener último tag
        id: lasttag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_OUTPUT

      - name: Obtener commits desde el último tag
        id: changelog
        run: |
          echo "RELEASE_BODY=$(git log ${{ steps.lasttag.outputs.tag }}..HEAD --pretty=format:'- %s')" >> $GITHUB_ENV

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.RELEASE_BODY }}
